#!/usr/bin/env bash
# This script is displaying bad luck for the 4th loop,good luck for the 8th Best School for the other loops
c=1
while [ $c -le 10 ]
do
echo "Best School"
(( c++ ))
if [ $c == 2 ]
then
echo "bad luck"
elif [ $c == 4 ]
then
echo "good luck"
else [ $c == 5 ]
echo "Best school"
fi
done
