#!/usr/bin/env bash
# This script is displaying bad luck for the 4th loop,good luck for the 8th Best School for the other loops
c=1
while [ $c -le 10 ]
do
echo "Best School"
(( c++ ))
if [ $c == 5 ]
then
echo "Bad luck"
else [ $c == 9 ]
then
echo “good luck”
fi
done
