#!/usr/bin/env bash
# This script is displaying bad luck for the 4th loop,good luck for the 8th Best School for the other loops
c=1
while [ $c -le 6 ]
do
echo "Best School"
(( c++ ))
if [ $c == 3 ]
then
echo "bad luck"
elif [ $c == 5 ]
then
echo "good luck"
else [ $c -le 1 ]
echo "Best School"
fi
done
