#!/usr/bin/env bash
# This script is displays 4 and then bad luck from China for the 4th loop,9 and then bad luck from Japan for the 9th loop,17 and then bad luck from Italy
c=1
while [ $c -le 10 ]
do
case "${numbers}"
in
if [ $c == 4 ]
then
echo "4"
print "bad luck from China"
elif [ $c == 6 ]
then
echo "9"
print "bad luck from japan"
else [ $c -le 1 ]
echo "17"
print "bad luck from italy"
fi
esac
done
